package com.awlsoft.asset.orm.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.awlsoft.asset.model.entry.response.BorrowTaskResponse;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BORROW_TASK_RESPONSE".
*/
public class BorrowTaskResponseDao extends AbstractDao<BorrowTaskResponse, Long> {

    public static final String TABLENAME = "BORROW_TASK_RESPONSE";

    /**
     * Properties of entity BorrowTaskResponse.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property TaskID = new Property(0, String.class, "taskID", false, "TASK_ID");
        public final static Property TASK_DEF_KEY_ = new Property(1, String.class, "TASK_DEF_KEY_", false, "TASK__DEF__KEY_");
        public final static Property BUSINESS_KEY_ = new Property(2, String.class, "BUSINESS_KEY_", false, "BUSINESS__KEY_");
        public final static Property Id = new Property(3, Long.class, "id", true, "_id");
        public final static Property Category_id = new Property(4, int.class, "category_id", false, "CATEGORY_ID");
        public final static Property EctID = new Property(5, String.class, "ectID", false, "ECT_ID");
        public final static Property Keeper_id = new Property(6, long.class, "keeper_id", false, "KEEPER_ID");
        public final static Property Borrow_no = new Property(7, String.class, "borrow_no", false, "BORROW_NO");
        public final static Property Count = new Property(8, int.class, "count", false, "COUNT");
        public final static Property Workarea_id = new Property(9, long.class, "workarea_id", false, "WORKAREA_ID");
        public final static Property Status = new Property(10, int.class, "status", false, "STATUS");
    }


    public BorrowTaskResponseDao(DaoConfig config) {
        super(config);
    }
    
    public BorrowTaskResponseDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BORROW_TASK_RESPONSE\" (" + //
                "\"TASK_ID\" TEXT," + // 0: taskID
                "\"TASK__DEF__KEY_\" TEXT," + // 1: TASK_DEF_KEY_
                "\"BUSINESS__KEY_\" TEXT," + // 2: BUSINESS_KEY_
                "\"_id\" INTEGER PRIMARY KEY ," + // 3: id
                "\"CATEGORY_ID\" INTEGER NOT NULL ," + // 4: category_id
                "\"ECT_ID\" TEXT," + // 5: ectID
                "\"KEEPER_ID\" INTEGER NOT NULL ," + // 6: keeper_id
                "\"BORROW_NO\" TEXT," + // 7: borrow_no
                "\"COUNT\" INTEGER NOT NULL ," + // 8: count
                "\"WORKAREA_ID\" INTEGER NOT NULL ," + // 9: workarea_id
                "\"STATUS\" INTEGER NOT NULL );"); // 10: status
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BORROW_TASK_RESPONSE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BorrowTaskResponse entity) {
        stmt.clearBindings();
 
        String taskID = entity.getTaskID();
        if (taskID != null) {
            stmt.bindString(1, taskID);
        }
 
        String TASK_DEF_KEY_ = entity.getTASK_DEF_KEY_();
        if (TASK_DEF_KEY_ != null) {
            stmt.bindString(2, TASK_DEF_KEY_);
        }
 
        String BUSINESS_KEY_ = entity.getBUSINESS_KEY_();
        if (BUSINESS_KEY_ != null) {
            stmt.bindString(3, BUSINESS_KEY_);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(4, id);
        }
        stmt.bindLong(5, entity.getCategory_id());
 
        String ectID = entity.getEctID();
        if (ectID != null) {
            stmt.bindString(6, ectID);
        }
        stmt.bindLong(7, entity.getKeeper_id());
 
        String borrow_no = entity.getBorrow_no();
        if (borrow_no != null) {
            stmt.bindString(8, borrow_no);
        }
        stmt.bindLong(9, entity.getCount());
        stmt.bindLong(10, entity.getWorkarea_id());
        stmt.bindLong(11, entity.getStatus());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BorrowTaskResponse entity) {
        stmt.clearBindings();
 
        String taskID = entity.getTaskID();
        if (taskID != null) {
            stmt.bindString(1, taskID);
        }
 
        String TASK_DEF_KEY_ = entity.getTASK_DEF_KEY_();
        if (TASK_DEF_KEY_ != null) {
            stmt.bindString(2, TASK_DEF_KEY_);
        }
 
        String BUSINESS_KEY_ = entity.getBUSINESS_KEY_();
        if (BUSINESS_KEY_ != null) {
            stmt.bindString(3, BUSINESS_KEY_);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(4, id);
        }
        stmt.bindLong(5, entity.getCategory_id());
 
        String ectID = entity.getEctID();
        if (ectID != null) {
            stmt.bindString(6, ectID);
        }
        stmt.bindLong(7, entity.getKeeper_id());
 
        String borrow_no = entity.getBorrow_no();
        if (borrow_no != null) {
            stmt.bindString(8, borrow_no);
        }
        stmt.bindLong(9, entity.getCount());
        stmt.bindLong(10, entity.getWorkarea_id());
        stmt.bindLong(11, entity.getStatus());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3);
    }    

    @Override
    public BorrowTaskResponse readEntity(Cursor cursor, int offset) {
        BorrowTaskResponse entity = new BorrowTaskResponse( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // taskID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // TASK_DEF_KEY_
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // BUSINESS_KEY_
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // id
            cursor.getInt(offset + 4), // category_id
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // ectID
            cursor.getLong(offset + 6), // keeper_id
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // borrow_no
            cursor.getInt(offset + 8), // count
            cursor.getLong(offset + 9), // workarea_id
            cursor.getInt(offset + 10) // status
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BorrowTaskResponse entity, int offset) {
        entity.setTaskID(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTASK_DEF_KEY_(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBUSINESS_KEY_(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setCategory_id(cursor.getInt(offset + 4));
        entity.setEctID(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setKeeper_id(cursor.getLong(offset + 6));
        entity.setBorrow_no(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setCount(cursor.getInt(offset + 8));
        entity.setWorkarea_id(cursor.getLong(offset + 9));
        entity.setStatus(cursor.getInt(offset + 10));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BorrowTaskResponse entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BorrowTaskResponse entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BorrowTaskResponse entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
