package com.awlsoft.asset.orm.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.awlsoft.asset.model.entry.response.UserResponse;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_RESPONSE".
*/
public class UserResponseDao extends AbstractDao<UserResponse, Long> {

    public static final String TABLENAME = "USER_RESPONSE";

    /**
     * Properties of entity UserResponse.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Office_id = new Property(0, int.class, "office_id", false, "OFFICE_ID");
        public final static Property Password = new Property(1, String.class, "password", false, "PASSWORD");
        public final static Property Login_name = new Property(2, String.class, "login_name", false, "LOGIN_NAME");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
        public final static Property Id = new Property(4, Long.class, "id", true, "_id");
    }


    public UserResponseDao(DaoConfig config) {
        super(config);
    }
    
    public UserResponseDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_RESPONSE\" (" + //
                "\"OFFICE_ID\" INTEGER NOT NULL ," + // 0: office_id
                "\"PASSWORD\" TEXT," + // 1: password
                "\"LOGIN_NAME\" TEXT," + // 2: login_name
                "\"NAME\" TEXT," + // 3: name
                "\"_id\" INTEGER PRIMARY KEY );"); // 4: id
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_RESPONSE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserResponse entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getOffice_id());
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(2, password);
        }
 
        String login_name = entity.getLogin_name();
        if (login_name != null) {
            stmt.bindString(3, login_name);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(5, id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserResponse entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getOffice_id());
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(2, password);
        }
 
        String login_name = entity.getLogin_name();
        if (login_name != null) {
            stmt.bindString(3, login_name);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(5, id);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4);
    }    

    @Override
    public UserResponse readEntity(Cursor cursor, int offset) {
        UserResponse entity = new UserResponse( //
            cursor.getInt(offset + 0), // office_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // password
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // login_name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // name
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserResponse entity, int offset) {
        entity.setOffice_id(cursor.getInt(offset + 0));
        entity.setPassword(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLogin_name(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UserResponse entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UserResponse entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserResponse entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
